### ISSUE TITLE
undo bought drink

### ISSUE THREAD

**Issue by Eichi** [Chaotikum/icebox-service#4]
I accidentally bought a drink in the name of another person *tüdü*.
How can i revert this or give the person the drink back?

**Comment by stroborobo** [comment]
Happened to me as well, but as anon. :)

**Comment by johthor** [comment]
For now the official answer is: _That won't happen_
So don't do this in the first place :-)

But we will look into this and find a way to undo certain actions.

**Comment by TVLuke** [comment]
Note that the service is currently "Icebox 0.1 - Alpha Kevin" and our focus is currently more on stability and bug fixing than on implementing new features. 

The current workarounds are as follows: 
- If you buy a drink for someone else, just talk to that person. Tell him or her to buy one on your account.
- If you buy a drink on anon, just buy that drink again. Yes, this will skew the data... Right now this doesn't matter much. If you feel like that is a problem, just use the icebox.nobreakspace.org website to correct the amount of remaining bottles.
- if you bought the wrong drink: Just correct the amounts for the drink you wanted and the drink you selected on icebox.nobreakspace.org

Undo will be added as a feature to be implemented in "Icebox 0.2 - Beta ..."

**Comment by TVLuke** [comment]
with bab2accf8acfc88ef9aef9dff873536bf6b80b9a undo is now available, consumptions can be deleted by using the _"undoparameters"_ returned when posting a consumption. This is documented in the API-documentation of the project http://docs.iceboxservice.apiary.io/#reference/0/consumtion.

Note: Undo can only be performed from the client that posted the original consumption-request. This is because the money has to be returned to the user and a user with the vds-flag set to false can not be identified by any other device than the client, since the server itself does not have any data on what consumer has bought a drink if this user has the vds-flag disabled.

Also Note: Just because the server has this feature now does not mean it is available on any client yet. It just means it can be implemented.
